write binary to action path

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -20,8 +20,12 @@ inputs:
 runs:
   using: "composite"
   steps:
-    - name: Verify Go SDK
-      run: which go || echo "Go required, please use actions/setup-go before me"
-      shell: bash
-    - run: (cd "${{github.action_path}}" && go build -o /action-update-go .) && /action-update-go
-      shell: bash
+  - name: Verify Go SDK
+    run: which go || echo "Go required, please use actions/setup-go before me"
+    shell: bash
+  - name: Compile action-update-go
+    run: cd "${{github.action_path}}" && go build -o ./action-update-go .
+    shell: bash
+  - name: Run action-update-go
+    run: pwd && "${{github.action_path}}/action-update-go"
+    shell: bash
